<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="CNS04" name="Login" tests="4" failures="1" timestamp="20 Jun 2018 12:32:56 GMT" time="64.742" errors="0">
  <testcase name="Test_Login_Validation" time="10.514" classname="com.qa.rd.scripts.CustomLoginTest"/>
  <testcase name="Test_Valid_Registration" time="9.731" classname="com.qa.rd.scripts.CustomLoginTest"/>
  <testcase name="Test_FB_Login_Validation" time="20.274" classname="com.qa.rd.scripts.CustomLoginTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
null">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
null
	at com.qa.rd.scripts.appModule.Login_Action.Test_FB_Login_Validation(Login_Action.java:159)
	at com.qa.rd.scripts.CustomLoginTest.Test_FB_Login_Validation(CustomLoginTest.java:71)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 17 stack frames]]>
    </failure>
  </testcase> <!-- Test_FB_Login_Validation -->
  <testcase name="Test_FB_Valid_Login" time="14.67" classname="com.qa.rd.scripts.CustomLoginTest"/>
</testsuite> <!-- Login -->
